site_name: Kubrick Competitor Profiling (Consultant Rates)
nav:
  - Home: index.md
  - Overview: 
    - Data Sources: data_sources.md
  - Technical:
      - Technical Overview: tech_overview.md 
      - Extractor: extractor.md
      - Rate Card Processor: rate_card_processing.md
      - Stats: stats.md
      - Support Functions: support_functions.md
      - Data Processing: dataprocessing.md
      - Apps: app.md
  - Planned Features : future_work.md
  - Issues Log: issues.md

extra_css:
  - docs/extra.css

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - search.highlight
    - content.code.annotate
    - palette.toggle


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            show_source: true

mkdocstrings:
  default:
    show_root: true

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true


